authors:
  gmauro:
    name: Gianmauro Cuccuru
    description: Creator
    avatar: https://github.com/gmauro.png
  Coordinamento:
    name: Coordinamento SdC
    description: Creator
    avatar: assets/images/logo_scontornato.png
